version: '3.8'

services:
    frontend:
        build: ./infoscreen-front
        ports:
            - '3000:3000'
        depends_on:
            - backend

    backend:
        build: ./infoscreen-backend
        ports:
            - '3001:3001'
        depends_on:
            - db

    db:
        image: mongo:latest
        volumes:
            - mongodb_data_container:/data/db
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword

volumes:
    mongodb_data_container:
